<?php

namespace app\api\controller\dev;


class Product extends Base
{

    private $model;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = model('Product');
    }


    public function index()
    {
        $this->data['data'] = $this->model->getProductList($this->params);
        return json($this->data);
    }

    public function details()
    {
        $this->data['data'] = $this->model->getProductDetail($this->params['goods_id']);
        return json($this->data);
    }

    /**
     * 获取活动商品
     */
    public function activity()
    {

    }
}
